---
- name: "Create RDS instance here"
  become: true
  rds:
    command: create
    instance_name: new-database
    db_engine: MySQL
    size: 10
    region: us-west-2
    instance_type: db.m1.small
    username: mysql_admin
    password: 1nsecure
    wait: yes
    tags:
      Environment: testing
  delegate_to: localhost

- name: "Print RDS endpoint"
  debug: msg="The new db endpoint is {{ rds.instance.endpoint }}"
