Feature: Get Conversations for a user

  Scenario: A user is able to retrieve the conversations successfully
    Given a user Alice already exists on the system
    And user Alice is successfully authenticated
    And the user Alice has some conversations available on the server
    When user Alice tries to access their conversations
    Then the user Alice should be able to receive their conversations in the response
    And a MESSAGE_READ_EVENT is generated by the application

  #User not found test