---
- name: "Create EC2 Key-Pair"
  ec2_key:
    name: "{{ key_pair_name }}"
    region: "{{ aws_region }}"
    key_material: "{{ item }}"
    state: present
  with_file: ~/.ssh/id_rsa.pub
  register: integration_key

- name: "Create Security Group"
  ec2_group:
    name: "{{ security_group }}"
    description: Security Group
    region: "{{ aws_region }}"
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: "Create VM"
  ec2:
    key_name: "{{ key_pair_name }}"
    instance_type: t2.micro
    region: "{{ aws_region }}"
    image: ami-b04e92d0
    wait: yes
    wait_timeout: 10000
    instance_tags:
      class: "{{ class_tag }}"
      tier: "{{ tier_tag }}"
  register: ec2_instance_info

- name: "Wait for SSH to come up"
  local_action: wait_for
                host="{{ item.public_ip }}"
                port=22
                state=started
  with_items: "{{ ec2_instance_info.instances }}"

- name: "Accept new ssh fingerprints"
  shell: ssh-keyscan -H {{ item.public_ip }} >> ~/.ssh/known_hosts
  with_items: '{{ ec2_instance_info.instances }}'

