---
- hosts: tag_class_integration_test_instance
  user: ec2-user
  gather_facts: true
  become: true
  roles:
#    - os_harden
#    - ec2_prepare
    - wordpress
  tasks:
    - name: "Check connections to Mysql"
      debug: msg="TODO Run Tests"

    - name: "Check connections to Wordpress"
      debug: msg="TODO "
