FROM fedora:25

MAINTAINER Gaurav Tyagi <aanconsultancyservicesltd@gmail.com>

RUN yum install -y vim && \
    yum install -y wget && \
    wget https://nginx.org/packages/rhel/7/x86_64/RPMS/nginx-1.12.0-1.el7.ngx.x86_64.rpm && \
    yum install -y nginx-1.12.0-1.el7.ngx.x86_64.rpm && \
    cd /opt && \
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz" && \
    tar xvfz jdk-8u121-linux-x64.tar.gz
    alternatives --install /usr/bin/java java /opt/jdk1.8.0_121/bin/java 2 && \
    useradd -m elasticsearch && \
    cd /home/elasticsearch && \
    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.tar.gz && \
    tar xvfz elasticsearch-5.4.0.tar.gz && \
    chown -R elasticsearch:elasticsearch elasticsearch-5.4.0 && \
    yum update -y

EXPOSE 80
EXPOSE 443


