
---
- name: "Add Mongo Repository to yum-config"
  yum_repository:
    name: MongoDB_Repository
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.2/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-3.2.asc

- name: "Install MongoTools"
  yum: name=mongodb-org-tools-3.2.11 state=present