package org.gt.chat.stepDefs;

import com.google.inject.Inject;
import cucumber.api.java.en.And;
import cucumber.runtime.java.guice.ScenarioScoped;
import org.gt.chat.main.audit.domain.TestAuditEvent;
import org.gt.chat.scenario.Context;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@ScenarioScoped
public class AuditStepdefs {
    private Context context;
    private DatabaseService databaseService;

    @Inject
    public AuditStepdefs(Context context,DatabaseService databaseService) {
        this.context = context;
        this.databaseService = databaseService;
    }

    @And("^a (.*) is generated by the application$")
    public void eventIsGeneratedByTheApplication(String eventType) throws Throwable {
        String requestId = context.getRequestId();

        List<TestAuditEvent> auditEvents = databaseService.findAuditEventFor(requestId, eventType);
        assertThat(auditEvents.size()).isEqualTo(1);
    }
}
