package org.gt.chat.stepDefs;

import com.google.inject.Inject;
import cucumber.api.java.en.And;
import cucumber.runtime.java.guice.ScenarioScoped;
import org.gt.chat.domain.audit.TestAuditEvent;
import org.gt.chat.scenario.Context;
import org.gt.chat.stepDefs.service.MockDatabaseService;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@ScenarioScoped
public class AuditStepdefs {
    private Context context;
    private MockDatabaseService mockDatabaseService;

    @Inject
    public AuditStepdefs(Context context,MockDatabaseService mockDatabaseService) {
        this.context = context;
        this.mockDatabaseService = mockDatabaseService;
    }

    @And("^a (.*) is generated by the application$")
    public void eventIsGeneratedByTheApplication(String eventType) throws Throwable {
        String requestId = context.getRequestId();

        Thread.sleep(1000);

        List<TestAuditEvent> auditEvents = mockDatabaseService.findAuditEventFor(requestId, eventType);
        assertThat(auditEvents.size()).isEqualTo(1);
    }
}
