# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

settings = YAML.load_file(File.join(File.dirname(__FILE__), 'ec2_access_keys.yml'))

options = {}
options[:zookeeper_url] = ENV['ZOOKEEPERHOST']
access_keys = settings['ec2']['access_key_id']
secret_access_keys = settings['ec2']['secret_access_key']

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  
  config.vm.box = "dummy"
	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.define "kafka-host-1" do |mh1|
    mh1.vm.provision "shell", path: "./provision/setupVM.sh", args: "#{options[:zookeeper_url]}, 1"
    end

  config.vm.define "kafka-host-2" do |mh2|
    mh2.vm.provision "shell", path: "./provision/setupVM.sh", args: "#{options[:zookeeper_url]}, 2"
    end

  config.vm.define "kafka-host-3" do |mh3|
    mh3.vm.provision "shell", path: "./provision/setupVM.sh", args: "#{options[:zookeeper_url]}, 3"
  end

  config.vm.provider :aws do | aws, override |
	aws.access_key_id = access_keys
	aws.secret_access_key = secret_access_keys
	aws.region = "us-west-2"

	aws.security_groups = ['Kafka']
	override.ssh.username = "ec2-user"
	override.ssh.private_key_path="/Users/gtyagi/personalWorkspace/online/DockerEnvironments/kafka/gtyagiawskey.pem"

	aws.region_config "us-west-2" do |region|
				region.ami = "ami-7172b611"
				region.instance_type = "t2.micro"
				region.keypair_name = "gtyagiawskey"
				region.security_groups = "Kafka"
	end
  end

end
